### ISSUE TITLE
Need help with how to edit certain areas of the site...

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-theme#1]
From Bill:
I’m struggling to modify some of the type blocks. None of the edit options which appear on the other pages appear for the home page. 

- Terms of Service and Privacy Policy pages
- Home Page - Experience section - subtitle “Exclusive features for collectors”  Can edit text but not height (it’s too small). Also the content is split in to 2 paragraphs in the description box, but appears as one block.
- How it Works page - content in the first major paragraph “We select iconic, must see…” should be the same as the content in the other sections, but it’s larger even though ‘Paragraph’ is selected as the size for them all. As an aside is there any way I can reduce the gap between that section and the ‘Importing the work’ section underneath please?
- Partners - Artists and Institutions - in both these sections when you go to the main bio page the logo and content is too large

**Comment by ocupopdev** [comment]
@ZiggyAtl These should all be updated now. Test and let me know.
See Pauls comment above on where to edit Terms of Service and Privacy Policy pages content.

**Comment by ZiggyAtl** [comment]
@ocupopdev With regard to the Terms of Service and Privacy, much of the formatting doesn't come across, and therefore the screen representation is different from the edit box in Settings-Policies. For instance check out the formatting in the Privacy Policy in the Collecting Personal Information section. The various bullets and indents haven't come across. Then when you get the paragraph heading 'Behavioral Advertising' it isn't in bold and the line return hasn't appeared.

**Comment by ZiggyAtl** [comment]
@ocupopdev please see update in bold below the original comment. 

Home Page - Experience section - subtitle “Exclusive features for collectors” Can edit text but not height (it’s too small). Also the content is split in to 2 paragraphs in the description box, but appears as one block.  
**Sorry but I still can't work out how to edit the height of that first subtitle “Exclusive features for collectors”, and now there's a large gap, which I don't want, between that and the text underneath.**

**Comment by ocupopdev** [comment]
@ZiggyAtl I pushed some updates to styling for elements on policies pages. 
I updated the spacing between "Exclusive features for collectors" and icons

**Comment by ZiggyAtl** [comment]
@ocupopdev looks much better, thanks! Just that last question outstanding about how I increase the height of the first subheading "Exclusive features for collectors" please? Its the same height as the content below it, and needs to be the same as the subheading below ("Each artwork includes a selection...")

**Comment by ZiggyAtl** [comment]
@ocupopdev to be honest, if i could increase the content height a little bit too it would be better. I'm just trying to recreate how it looked originally (see screenshots). As this new font seems to be breaking up and harder to read it would be better if that content could be a touch larger (the same height it was in the original version). And if there's any way of closing the gaps further (to match the original) that would be fantastic. 
![Original](https://github.com/user-attachments/assets/09203b80-cfa9-4ce3-bed2-96cbf261baad)
![Current](https://github.com/user-attachments/assets/62e7d322-5571-4965-aa12-1dab31557a3b)

**Comment by ZiggyAtl** [comment]
@jonathanwburr  here were two of the pages I found where the formatting in Shopify-theme doesn't show on the live site; 
 museum-overview &  Virtual Gallery Overview.  If it's a setting thing or a simple fix I'm happy to fix these if you let me know.

**Comment by ocupopdev** [comment]
@ZiggyAtl I made some adjustments to the experience section spacing. 
I made some style updates to how lists are displayed in general. It looks like the museum overview is showing lists with bullets now. 
Can you point me to the url of the virtual gallery overview page?

**Comment by ZiggyAtl** [comment]
@ocupopdev it's something you see in the customer account area if they've bought a DAB that also comes with a digital file to create their own virtual gallery. If you log in to my account - email bill@comission.art, password  Museumapp!0G1n# you'll be able to access it there

**Comment by paulstroot** [comment]
Virtual Gallery page: https://comission.art/pages/virtual-gallery-instructions

**Comment by jonathanwburr** [comment]
@ZiggyAtl @paulstroot the copy styles for the virtual gallery page should be updated now

**Comment by ZiggyAtl** [comment]
@paulstroot @jonathanwburr.  perfect, thanks
