### ISSUE TITLE
Account creation process

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-theme#10]
On the Password creation box when someone is creating an account there is no requirement to type it a second time, or even for them to view what they’re typing. Is it an easy thing to add this (or at least one of those features)? 

[edit: moved additional text here to issues #16 and #17 ]

**Comment by paulstroot** [comment]
This would take some time and is out side of our scope.

**Comment by ZiggyAtl** [comment]
OK, thanks
