### ISSUE TITLE
Shopify order processing

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-theme#11]
I’ve been doing all the testing on Village is Family so I decided to do a test order on the second piece of artwork on the system, called Free. Unlike Village, this one shows a ‘Ship to’ address, asks me to select Shipping Method in the check out screen, and has the ‘Use shipping address as billing address’ option box. Why is it doing this and how do we set the system to never involve any of the shipping aspects?

The following has been moved to issue #15 
Now that we're on comission.art I turned the option on in Order Processing to ‘Automatically fulfill the orders line items’ and to ’Notify customers of their shipment’ but I am still not getting the emailed receipt, although once the order is placed it does show as fulfilled in the order screen. Heads up the email was coming through OK when it was set to manually fulfill and I was processing them that way.

**Comment by ZiggyAtl** [comment]
@paulstroot sorry to be a nuisance, but I've spent over an hour on this and can't find it anywhere. When I select the piece in the Products section no shipping info comes up. I've done some research and believe it's usually under the pricing and inventory section, but there is nothing there. I checked to make sure it's active and it is. If there is no shipping info displayed I believe it might be because the product type is set to something that doesn't have shipping options, such as a digital product or a service. But if that were the case then the shipping options wouldn't come up at check out. I also checked the product type and it is set to Artwork, the same that I have always used. The final bit of advice I can find is that sometimes a theme or app might override certain product options. Any idea?

**Comment by paulstroot** [comment]
Look under the "variants" section. For the image attached, you can click "pricing tier 1" or "pricing tier 2". The following page should have the "this is a physical product" checkbox

![image](https://github.com/user-attachments/assets/c507ac74-0f35-43ca-8cc1-911ef4f264db)

**Comment by ZiggyAtl** [comment]
@paulstroot   Thanks. For some random reason one of the variants had the box ticked, with a zero weight
