### ISSUE TITLE
hCaptcha

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-theme#12]
Sales channels-online store-Preferences- it says hCaptcha is on for contact and comment forms, and for login create account and password recovery, but it hasn’t asked me to complete a hCaptcha task when doing anything in the site so far.

**Comment by paulstroot** [comment]
I have gotten the hcaptcha to show up for me. I believe it is usually hidden unless the javascript is not 100% certain that it is a human. if you start trying to submit forms with blank fields you may start seeing the captcha.

**Comment by ZiggyAtl** [comment]
@paulstroot odd I've been submitting forms with zero info in, and messed around with the sign up process when I was testing it, but haven't once seen it. Maybe there's a cookie on my laptop and phone which the site recognizes and validates? I'll ask a new tester to do the same and it will probably appear for them
