### ISSUE TITLE
Selecting items in mobile version

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-theme#13]
On mobile when I am using the DAB selector, anything more than a very quick tap on the screen selects the entire image. I suspect people won't realize this and therefore not be able to select a DAB. From memory didn’t we get rid of that issue once before?

**Comment by tbeck** [comment]
Hi Bill,
We have optimized the DAB selector several times and desktop has always been the priority. We are happy to continue to evolve this and even consider implementing a unique UI for mobile experience. However... this will need to be included in our next scope of work.

Let's connect after you launch and discuss what the next steps might include.
