### ISSUE TITLE
Make "Create Account" stand out more

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-theme#16]
Also on the Log In page I’ve tried to make the ‘Create Account’ text stand out a bit more (larger, bolder, maybe in all caps etc) but can’t figure out how to select and change that text. Is it easy to do?

**Comment by paulstroot** [comment]
This is coded directly into the page HTML. I made an update for you to make it more button-like. Please review and close if this works for you.

**Comment by ZiggyAtl** [comment]
@paulstroot Thank you
