### ISSUE TITLE
Account buttons not working on mobile

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-theme#18]
The ‘Sign In’ button doesn’t appear to be working on the Login page, or the ‘Submit’ on the Reset your Password page, or the ‘Create’ button on the Create Account page.

**Comment by paulstroot** [comment]
I was able to recreate this if none of the form fields were filled in, but if I entered anything into the fields it submits okay. Is this the same results you are getting @ZiggyAtl ?

**Comment by jonathanwburr** [comment]
@paulstroot I disabled hcaptcha on login, create account and password recovery pages to see if resolves issue.
Setting is in online store > preferences > spam protection > enable hcaptcha on login

**Comment by ZiggyAtl** [comment]
@paulstroot  @jonathanwburr I think that was the answer. I had been trying it again with no success a little while ago, and to answer Paul's question, it was happening when all the information was filled in all the fields. I even had someone else try it with my phone last night and they got exactly the same results. And then I tried it again at 6:30pm EST (8 mins ago) and it worked perfectly. So is hcaptcha the culprit?

**Comment by jonathanwburr** [comment]
@ZiggyAtl yes seems as though it was.
