### ISSUE TITLE
Need help with how to turn of automatic fulfillment

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-theme#2]
**From Bill:**
I got the welcome email (shopify notifications - order confirmation) but i didn’t get the email with the tax receipt (shopify notifications -  shipping confirmation). For that to go out i know the "automatically fulfill" option needs to be selected but when i got to settings - checkout i saw this message below. Does this refer to some of the custom scripts we can now do without? I didn’t want to go any further with this one without checking with you.
 
**Reply From Paul:**
I was also noticing that the "shipping confirmation" email was not being sent out when the order was fulfilled. I reached out to Shopify support and they gave me some details on this. Long story short, it has to do with our domain name DNS, and the email address that is sending the outgoing emails. They informed me that once we link the site up to our custom domain (comission.art) the emails should send properly.

In the meantime, the emails do get sent out if you fulfill the orders manually by going into the orders admin page and clicking "fulfill order”

**Reply from Bill**
I tried to do that but the order was automatically fulfilled, and I couldn’t edit it once it had been fulfilled. So I thought I’d turn the auto fulfill option off and put a new order through just to test it. But I’ve looked everywhere and can’t find anywhere I can alter the setting to allow me to manually fulfill. At the bottom of the Settings - Checkout page it refers to Order Status Page Additional Scripts. Is that anything to do with it? I suppose if it will work once once the site is linked to the custom domain it’s not an issue. I just wanted to test it to be sure.

**Comment by ZiggyAtl** [comment]
Hi @paulstroot  I had already closed that one as completed when you assigned it to me. Is that OK?

**Comment by paulstroot** [comment]
Perfect. Thanks!
