### ISSUE TITLE
Wording on Twitter/X Post

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-theme#22]
**From Bill:**
the autogenerated post is cut short.

**Reply From Paul:**
 This is because twitter has a limit of 280 characters, and the art title "Village is Family (for testing)" is pretty long. I suggest we drop the part "and @TheKingCenter has a donation in my name.’", which should bring the copy down to under 280 characters after we remove the "testing" from the art name.

**Reply From Bill**
I definitely want the donation info in there. An aspect of my target market is their need to brag about their altruism. I’m working on the wording for it and will send it through shortly.

**More from Bill:**
@paulstroot this is in relation to my last comment where I talked about the wording for the social posts.

![image](https://github.com/user-attachments/assets/39845c23-402d-402b-911b-3960323c9cef)

I've been thinking about the fact that often there are multiple recipients of the donations, and how to promote that by using the functionality we have. My thought is that each artwork can be tagged with various collections, so if the X post picked up the X handles of all tagged organizations that would achieve what I want. Same would apply for the suggested post it creates for instagram. Is that OK?

I realize that there are also some collections tagged which are our own internal ones (Home Page, View Artworks etc), but I'm assuming that as those don't have anything in the X & Instagram metafield, they'll just not be mentioned in the post?

**Comment by paulstroot** [comment]
A couple things here Bill. 

1. First, Thank you for following up on the length of the twitter/X message. you are right in that there should be plenty of characters available to fit our entire message. I dug deeper and discovered that the message was not being cut off because of a character limit, but because our character "#" was causing issues. This has been fixed.
 
3. That aside, you also mentioned adding multiple donation recipients to the message. We do not have a method to assign an artwork to multiple institutions right now, sorry. 

4. We do not have a character limit for instagram, so we don't need to worry about updating that one, although I did discover a bug that was preventing the last section about the donation from appearing. I've fixed that.

**Comment by ZiggyAtl** [comment]
@paulstroot  with regard to #2 don't we assign an artwork to multiple institutions through the collections system where we tag the artwork with all the relevant institutions it's connected to?

**Comment by paulstroot** [comment]
No. The original intention is that each artwork would only be owned by one museum. The scope has not changed to be able to assign multiple museums (now institutions) to an artwork.

**Comment by ZiggyAtl** [comment]
@paulstroot  ok. I've got to acknowledge the others though, so for the launch until I can get it changed, can the institutions be added as part of the standard text in each post? The instagram version would look like this;

Check out my new art ‘[ARTWORK TITLE]’ by [ARTIST NAME] that I’ve just bought from @CoMission.Art. DAB #[DAB #] has my name on it and @WellspringLiving @TheKingCenter @TheAshleyBella have donations in my name. #artforgood

**Comment by paulstroot** [comment]
While this is possible, it is not a trivial lift, and would involve a fair amount of work to change the logic in several places on our site. There would also be a significant lift to the museum app, as currently access to artworks are dependent on it being assigned to a single museum/institution.

**Comment by ZiggyAtl** [comment]
@paulstroot again, I think we might be at cross purposes here. My suggestion is that for the launch everything other than the elements in brackets, including those social handles, are fixed content. The system would therefore only be customizing the post with the artwork title, artist name and DAB#, which I believe it already does. We can then look at how to address the other institution bit after launch. Are we on the same page?

**Comment by paulstroot** [comment]
Yes! If you would like me to hardcode "@WellspringATL @TheKingCenter @TheAshleyBella" into the post, I can absolutely do that! I'm sorry if I was misunderstanding your request.

This will require a developer to go in and change the code in the future if you want to change it to something different, is that your intention? let me know and I'll make that change right away.

**Comment by ZiggyAtl** [comment]
@paulstroot yes please, unless you can think of a better easy way of doing it that I've overlooked. It's essential that we have those three listed

**Comment by paulstroot** [comment]
Done!
