### ISSUE TITLE
Facebook Social Media Link

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-theme#23]
**From Bill:**
> Facebook link doesn’t generate the text for the post, like the X one does. Also the link it posts just takes someone to the artwork page for that piece, not to their certificate

**Reply From Paul:** 
>  We can not explicitly pass in a custom title and description to facebook, it is taken from the meta information built into the page. because our page is dynamic, displaying different certificate information based on the parameters sent in the URL, this makes it difficult to have a custom facebook share URL for each certificate. I made a compromise here and decided to have facebook share the artwork page.

**Reply from Bill:**

>  Sorry you lost me a little there lol. So you’re saying we can’t do what we do with X and produce a post with a link to a website and custom wording? Obviously I’d rather have both, but if you’re saying it’s an either/or I agree it’s better to have the link to the certificate page that we use in the X post

**Comment by paulstroot** [comment]
You are right in that the first version of the facebook share link did allow us to share the certificate page. Now that we have migrated over to using Shopify to build out the pages, there is a limitation of how Shopify builds out it's dynamic URLs and Routes. The ID we pass to the certificate page will no longer tell facebook that it is a page unique from the other certificate pages, and facebook will serve up the wrong information on the share link.

We do have the opportunity to share the product page of the artwork that the user purchased though, which I think is a great option, as it engages the user directly with the page that allows them to interact with the art and make a purchase.

Flagging @tbeck for visibility so you can continue talking through with him for a possible solution in the future.

**Comment by ZiggyAtl** [comment]
@paulstroot thanks for that. I hadn't realized that was now a limitation, and was wondering why we weren't just doing the same as before. On that basis you're right and linking the product page is the best option.
