### ISSUE TITLE
Issues when checking out when not logged in.

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-theme#4]
**From Bill:**
I realized it had allowed me to purchase a dab without being logged in to my account, or creating one if i didn’t have one, so in the settings - checkout screen i selected “require customers to log in to their account before checkout”. I then tried to process another order, and got as far as the screen where i clicked the accept terms box and then the go to checkout box and then got this screen

**Reply from Paul:**
We have updated some of the configuration so that if a user is not logged in when they go to check out they will be redirected to a page asking them to either log in or create an account. 

**Reply From Bill:**
I was able to successfully buy a DAB while logged in to my account, but when I tried to buy one without being logged in it produced this on the screen once I had hit Checkout from the Cart screen
![image](https://github.com/user-attachments/assets/992332dd-e541-4bbf-9f5e-d41fc2471402)

**Comment by paulstroot** [comment]
@ZiggyAtl , could you try this again on your end? Maybe try in an incognito window?

**Comment by ZiggyAtl** [comment]
@paulstroot I tried it 4 times using an incognito window and the following happened;
I clicked on See Artworks - Village is Family view details button - Select Your DAB button - I then selected a DAB and clicked on Purchase - and then I got this message on the screen 
![Screen Shot 2024-11-19 at 2 11 53 PM](https://github.com/user-attachments/assets/0f602d61-1923-4415-aefe-a256cbe20b81)

**Comment by ZiggyAtl** [comment]
@paulstroot I just tried it again using a regular Chrome window (not incognito) and got the same result I previously mentioned. The screen does open up for a split second in the check out screen before that error message comes up (comission-art.myshopify.com refused to connect)

**Comment by paulstroot** [comment]
Note: Stepped through this on a video call with Bill and resolved.
