### ISSUE TITLE
Addition of MixPanel tracking pixel

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-theme#6]
**Note from Paul to Bill:**
One of the scripts was a pixel tracking code from "MixPanel". Is this tracking pixel something that you had requested form the start, and is it something that is still needed? Or is it okay to remove?

**Response from Bill:**
I believe that was one we had included to be able to use Mix Panel. Is it OK to leave it in there?

**Comment by paulstroot** [comment]
I've done some digging into this. Shopify has updated the way that it has integrated tracking pixels on it's sites. Instead of being able to place this code into a page, it needs to be implemented in a special section of the code, and hook into different events. (i.e. purchase made, contact form submitted, etc.). These events don't expose user information, which is a key element in the MixPanel integration.

This can be done, but it requires a fair amount of work to and finding the correct documentation. There are also 3rd party plug-ins for Shopify to easily integrate MixPanel across the entire site, but they come with a monthly fee.

I'd suggest that since you are not actively using MixPanel, that we table this feature for now, and can revisit if the need arises. Does that sound okay to you?

**Comment by ZiggyAtl** [comment]
OK with me
